package leedCode;

import java.util.Arrays;

public class FindTheDifference {
    /*
    You are given two strings s and t.

        String t is generated by random shuffling string s and then add one more letter at a random position.

        Return the letter that was added to t.

        Example 1:
        Input: s = "abcd", t = "abcde"
        Output: "e"
        Explanation: 'e' is the letter that was added.

        Example 2:
        Input: s = "", t = "y"
        Output: "y"
     */
    public static void main(String[] args) {
        String str1 = "";
        String str2 = "a";

        System.out.println(findTheDifference(str1, str2));

    }
    public static char findTheDifference(String s, String t) {

        char result = 0;

        for (char c : s.toCharArray()) {
            result ^= c;
        }


        for (char c : t.toCharArray()) {
            result ^= c;
        }


        return result;
    }
}
